# Generated by Django 5.2.5 on 2025-11-16 20:21
from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20, blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=50, blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=models.CASCADE, related_name='custom_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
